# Generated by Django 2.0.4 on 2018-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='can_post',
            field=models.BooleanField(default=False),
        ),
    ]
