version: "3.1"

volumes:
  database:
  redis-data:
  static:

services:
  django:
    build:
      context: ""
    env_file:
      - ./.env
    environment:
      DJANGO_ENV: production
    ports:
      - "8000:8000"
    volumes:
      - static:/usr/src/backend/static

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/logs
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./ssl/etc/letsencrypt/live/perunews.xyz/fullchain.pem:/etc/letsencrypt/live/perunews.xyz/fullchain.pem
      - ./ssl/etx/letsencrypt/live/perunews.xyz/privkey.pem:/etc/letsencrypt/live/perunews.xyz/privkey.pem
      - static:/usr/share/nginx/html/static

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379"
    volumes:
      - redis-data:/data

  postgres:
    env_file:
      - ./.env
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data