version: "3.1"

volumes:
  database:
  redis-data:

services:
  django:
    image: perunews/django
    build:
      context: .
    env_file:
      - ./dev.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/server

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379"
    volumes:
      - redis-data:/data

  postgres:
    env_file:
      - ./dev.env
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data